import { generateFinalContent } from '../generateFinalContent';

describe('generateFinalContent', () => {
  it('should generate the final content correctly', () => {
    const name = 'mySnippet';
    const prefix = 'my-prefix';
    const body = '// testing;\nconsole.log("Hello, World!");';

    const expected = `{
  // This file was generated by Create Snippet Wizard.
  // Create Snippet Wizard is a VSCode extension that allows you to create code snippets.
  // https://marketplace.visualstudio.com/items?itemName=LuizImbroisi.vscode-extension-snippet-wizard
  
  "mySnippet": {
    "scope": "html, javascript, typescript, javascriptreact, typescriptreact",
    "prefix": "my-prefix",
    "body": [
      "// testing;",
      "console.log(\\"Hello, World!\\");"
    ]
  }
}
`;

    const result = generateFinalContent(name, prefix, body);
    expect(result).toBe(expected);
  });
});
